#!/usr/bin/env python3

import rospy
from agimus_controller_ros.agimus_controller import (
    AgimusControllerNode,
    AgimusControllerNodeParameters,
)


def run():
    rospy.init_node("talker", anonymous=True)
    params = AgimusControllerNodeParameters(use_ros_params=True, params_dict=None)
    node = AgimusControllerNode(params)
    node.run()


if __name__ == "__main__":
    try:
        run()
    except rospy.ROSInterruptException:
        pass
