#!/usr/bin/env python3

import rospy
from agimus_controller_ros.hpp_agimus_controller import HppAgimusController
from agimus_controller_ros.parameters import AgimusControllerNodeParameters


def run():
    rospy.init_node("talker", anonymous=True)
    params = AgimusControllerNodeParameters()
    params.set_parameters_from_ros()
    node = HppAgimusController(params)
    node.run()


if __name__ == "__main__":
    try:
        run()
    except rospy.ROSInterruptException:
        pass
