#!/usr/bin/env python3

import rospy
from agimus_controller_ros.hpp_agimus_controller import HppAgimusController


def run():
    rospy.init_node("talker", anonymous=True)
    node = HppAgimusController()
    node.run()


if __name__ == "__main__":
    try:
        run()
    except rospy.ROSInterruptException:
        pass
