#!/usr/bin/env python3

import rospy
from agimus_controller_ros.hpp_subscriber import HPPSubscriber

def run():
    rospy.init_node('talker', anonymous=True)
    sub = HPPSubscriber()
    rate = rospy.Rate(100)

    while not rospy.is_shutdown():
        tp = sub.get_trajectory_point()
        print("tp.q = ", tp.q)
        print("tp.v = ", tp.v)
        print("tp.a = ", tp.a)
        # print("tp.tau = ", tp.tau)
        # print("tp.com_pos = ", tp.com_pos)
        # print("tp.com_vel = ", tp.com_vel)
        # print("tp.op_pos = ", tp.op_pos)
        # print("tp.op_vel = ", tp.op_vel)
        # print("tp.time = ", tp.time)
        print("#______________")
        rate.sleep()


if __name__ == '__main__':
    try:
        run()
    except rospy.ROSInterruptException:
        pass